# Generated by Django 4.2.8 on 2023-12-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='date',
        ),
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
