# Generated by Django 4.2.8 on 2023-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_expenses_name_remove_expenses_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
