# Generated by Django 4.2.8 on 2023-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwordresetcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=50)),
                ('time', models.DateTimeField()),
                ('code', models.CharField(max_length=128)),
                ('username', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
